Ticket methods to encrypt and decrypt ticket id, and method to find encrypted ticket id.
BadChoice/handesk-php pull request #8
Opened 2021-01-26 15:20 UTC by aleixgil

Linear: https://linear.app/revo/issue/REV-2544/handesk-php-encrypt-and-decrypt-ticket-id

En comptes de posar una pwd al .env he fet una encriptació directe de la id. No li trobo molt sentit a lo del .env.
**Penja tag/versió si esta bé!**

2021-01-27 15:41 UTC, BadChoice requested changes

2021-01-27 15:41 UTC, BadChoice commented on src/Ticket.php
> +        return decrypt($id);
d'on agafa la key per encriptar/desencriptar?

2021-01-27 15:44 UTC, aleixgil commented on src/Ticket.php
> +        return decrypt($id);
No agafa ninguna key, és lo que et vam comentar el Pau i jo. Faig un encrypt i un decrypt amb els methodes de laravel. Lo de la contrasenya al .env no li veig molt sentit...

2021-01-28 08:54 UTC, aleixgil commented on src/Ticket.php
> +        return decrypt($id);
@BadChoice Important penjar versió/tag i també penjar-ho al RVPods de bitbucket!!

2021-01-28 08:56 UTC, aleixgil commented on src/Ticket.php
> +        return decrypt($id);
@BadChoice Important penjar versió/tag ja llest per actualitzar al back de xef i retail!!

2021-01-28 09:21 UTC, BadChoice requested changes

2021-01-28 09:21 UTC, BadChoice commented on src/Ticket.php
> +        return decrypt($id);
no entenc perque ho has afegit aquí si no es fa servir enlloc dins d'aquest projecte

2021-01-28 09:31 UTC, BadChoice approved these changes

2021-01-28 09:31 UTC, merged